name: Build SSH Easy
on:
  workflow_dispatch:
  push:
    branches: [ main ]

permissions: 
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ssheasy

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Extract metadata (tags, labels) for Docker
      id: meta-web
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ github.actor }}/${{ env.IMAGE_NAME }}
        tags: |
          type=raw,value=web
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        file: ./nginx/Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ steps.meta-web.outputs.tags }}
        labels: ${{ steps.meta-web.outputs.labels }}
    - name: Extract metadata (tags, labels) for Docker
      id: meta-proxy
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ github.actor }}/${{ env.IMAGE_NAME }}
        tags: |
          type=raw,value=proxy
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: ./proxy
        provenance: false
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ steps.meta-proxy.outputs.tags }}
        labels: ${{ steps.meta-proxy.outputs.labels }}
